### ISSUE TITLE
web 端（非公众账号web页面）访问数据库的一个问题

### ISSUE THREAD

**Issue by bestvayne** [TencentCloudBase/cloudbase-extension-cms#101]
开发环境：vue
SDK: @cloudbase/js-sdk
数据库是小程序端创建，并且可以登录 CMS 地址对数据库内容进行操作

问题描述：
在本地开发时，通过 localhost:8080 可以在页面上正常访问，但是部署以后，提示报错，跨域
![image](https://user-images.githubusercontent.com/11917682/114902639-9768e500-9e48-11eb-908d-10c2d108221e.png)

目前的需求，就是希望可以在一个 web 端页面对这个云开发数据库进行操作

**Comment by chhpt** [comment]
请到云开发控制台添加 Web 安全域名
