### ISSUE TITLE
如何支持管理已有的云开发数据

### ISSUE THREAD

**Issue by zuohuadong** [TencentCloudBase/cloudbase-extension-cms#103]
原先数据库的字段应当如何导入？
文档中好像没有相关的

**Comment by chhpt** [comment]
请查看文档说明：https://docs.cloudbase.net/cms/tutorial/quick.html

**Comment by zuohuadong** [comment]
> 请查看文档说明：https://docs.cloudbase.net/cms/tutorial/quick.html

文档中并没有说明，在已有云数据库表结构上（非CMS创建）如何导入。
