### ISSUE TITLE
已有系统，“支持管理已有的云开发数据”如何做？

### ISSUE THREAD

**Issue by zuohuadong** [TencentCloudBase/cloudbase-extension-cms#104]
请查看文档说明：https://docs.cloudbase.net/cms/tutorial/quick.html

文档中并没有说明，在已有云数据库表结构上（非CMS创建）如何导入。

已有的数据库导出 json ，再导入CMS 模型提示非法json 字符串。

**Comment by chhpt** [comment]
@zuohuadong 文档中已经说明了如何管理已有的数据

**Comment by zuohuadong** [comment]
@chhpt  已经找了好几天了，官方给的文档中确实没有。

**Comment by chhpt** [comment]
@zuohuadong 你还没有建立模型，请根据文档说明操作：https://docs.cloudbase.net/cms/tutorial/quick.html
