### ISSUE TITLE
内容模型(内容集合)希望可以排序

### ISSUE THREAD

**Issue by williambao** [TencentCloudBase/cloudbase-extension-cms#109]
希望内容模型里的模型可以排序。 目前新加的内容模型自动排到最后。 
内容集合里的也希望跟着能排序。

**Comment by chhpt** [comment]
重复 #37

**Comment by williambao** [comment]
@chhpt 和37不同。 37是一个内容模型里的字段排序。
如下图中【15天内到期订单】，想把它列到最上面。
![image](https://user-images.githubusercontent.com/779521/117980491-9901cc00-b366-11eb-8833-5aae857838d6.png)
