### ISSUE TITLE
希望能增加自定义表单组件功能

### ISSUE THREAD

**Issue by lockdown56** [TencentCloudBase/cloudbase-extension-cms#115]

**Comment by chhpt** [comment]
需求不清楚

**Comment by lockdown56** [comment]
> 需求不清楚

比如：
创建内容模型时，要添加地址相关字段（地址，经纬度），然后希望是通过地图点选的方式获取地址信息。
类似这种的需求，是否可以自己开发插件的方式实现，官方要满足所有需求确实工作量有点大
