### ISSUE TITLE
[Feature Request] 图片、文件数组支持 请加快呀加快呀

### ISSUE THREAD

**Issue by yekai9527** [TencentCloudBase/cloudbase-extension-cms#12]
腾讯云热心用户!
CMS重度用户来拉!
在GIT上这么说是不是显得很不专业
不过真的超级喜欢腾讯云
云开发真的是给广大个人开发者解决了大问题!

感谢腾讯云团队

2.0的功能设计已经已经非常非常贴近我们的使用了
有些功能的设计简直已经把我融化了

这个issue主要是催一下进度(我真不要脸)

第一重要的功能

*图片、文件数组支持	🏹 设计中

接下来这个也很重要

*支持复杂的对象，支持复杂数组类型，支持对象嵌套类型，JSON	🏹 设计中	
	
请开发老大尽快将这两个设计中的功能搞定 尽快发布2.0

祝你们工作顺利
谢谢

**Comment by zhifengjiang** [comment]
同样，我们的业务只有“支持复杂的对象，支持复杂数组类型，支持对象嵌套类型，JSON”这个功能上线后才能使用CMS

**Comment by yekai9527** [comment]
感觉这个可以关闭了,优秀的roadmap以及快速的迭代速度
优秀的团队
优秀的开源项目
多少个star都值得给呀

**Comment by chhpt** [comment]
图片、文件数组已支持
