### ISSUE TITLE
CMS 内容管理 内容类型 图片 上传 0%

### ISSUE THREAD

**Issue by xiaohongcoder** [TencentCloudBase/cloudbase-extension-cms#121]
![微信截图_20210609104017](https://user-images.githubusercontent.com/61079864/121284468-7801ac00-c90f-11eb-824f-bece347511e7.png)

![2](https://user-images.githubusercontent.com/61079864/121284481-7cc66000-c90f-11eb-8fa5-3777284d692d.png)

我和我的小伙伴一起发现的

还需要补充更多信息吗

Google Chrome 已是最新版本
版本 91.0.4472.77（正式版本） （64 位）

**Comment by chhpt** [comment]
请将云存储的权限设置为所有人可以上传
