### ISSUE TITLE
【功能建议】字段排序，option可选项，以及关联查询的问题！

### ISSUE THREAD

**Issue by iblackly** [TencentCloudBase/cloudbase-extension-cms#13]
一些功能建议，希望采纳~

**一：字段排序**
![enter image description here](https://s1.ax1x.com/2020/09/20/wofTTe.jpg)
新加入了一个字段(前面已有N个字段)，
而新加入的字段是需要排在靠前的位置！

**二：字段选择项**
![enter image description here](https://s1.ax1x.com/2020/09/20/wofowD.jpg)
一个字段内的填的东西是固定的几十个值~
所以可以整个option吗？

**一些问题**
还有小程序用云开发关联查询总感觉，，，，
我遇到的问题...

[如何一次查询N个集合内指定的数据？](https://developers.weixin.qq.com/community/develop/doc/0004cedf46c0907609ea1324b56000)

[如何'优雅'的获取多集合数据？](https://developers.weixin.qq.com/community/develop/doc/000c024a2d4000c967fa8a8dc51c00)

**Comment by chhpt** [comment]
@iblackly 1. 字段排序大概会在 2.1 版本支持 2. 建议你可以使用 Enum，枚举类型

**Comment by chhpt** [comment]
@iblackly 第 3 点，如何 '优雅' 的获取多集合数据，这个是数据库的设计问题
1. 如果分集合存储的话，必然就需要跨表查询，就需要使用 lookup
2. 或者可以从设计上改变，将 save 的数据冗余存储到 save 字段中，即  save 是个对象，不是个 id

**Comment by iblackly** [comment]
@chhpt 好的大佬，明白了，非常感谢！
