### ISSUE TITLE
webhook的使用示例

### ISSUE THREAD

**Issue by shenghanqin** [TencentCloudBase/cloudbase-extension-cms#2]
在cms后台支持了webhook的入口，但并未给出相应的用法示例。

期望，能给出完整示例。

**Comment by shenghanqin** [comment]
@chhpt 这个规划了吗？

**Comment by shenghanqin** [comment]
@chhpt webhook文档略简单哟。

https://github.com/TencentCloudBase/cloudbase-extension-cms/blob/feat/v2/docs/webhook.md

**Comment by chhpt** [comment]
@shenghanqin Webhook 本身也不复杂

**Comment by chhpt** [comment]
已提供：https://docs.cloudbase.net/cms/webhook.html
