### ISSUE TITLE
[feature request]有一个使用体验上不便的地方

### ISSUE THREAD

**Issue by yekai9527** [TencentCloudBase/cloudbase-extension-cms#36]
首先感谢腾讯云开发,感谢提交了历史性更新,支持文件数组和图片数组的 无亦杨 
感谢腾讯云的快速反馈以及辛苦的程序员 
CMS已经投入我们的实际生产中,获得了大家的交口称赞

前端开发很快乐,不用写管理界面了; 
数据整理小姐姐很开心,因为可以和开发同步修改数据,提前开始,再也不用加班了

在实际使用中,我们遇到一个新的问题,这个是我家整理数据的小姐姐强烈要求的

**使用场景如下:**

我们要对原始数据做修改 大概1000多条 这个是需要工作人员手工操作的,每一条都要操作

在进入列表页操作的时候, 我们设置的每页50条,从大概第十页开始编辑,假设我们编辑第485条

核对完数据以后,修改提交,会跳转到列表页第一页,这时候每页显示10条,这样很难快速找到第486条继续编辑

**希望变成:**

 在提交以后,保留每页50条,还是留在第十页,这样在编辑完485条以后,可以紧接着编辑486条

诚恳请求大佬考虑下.感谢!

**Comment by chhpt** [comment]
@yekai9527 已加入计划中

**Comment by chhpt** [comment]
@yekai9527 已在 v2.1.2 中发布
