### ISSUE TITLE
枚举选择数字或字符串保存后在编辑仍然提示元素值类型

### ISSUE THREAD

**Issue by iblackly** [TencentCloudBase/cloudbase-extension-cms#39]
但实际上已经是字符串或数字了！

![Image of Yaktocat](https://i.loli.net/2020/10/17/GunlAXZFkxBbwdm.png)
![Image of Yaktocat](https://i.loli.net/2020/10/17/lp8dDj1sSkhPtX7.png)

**Comment by chhpt** [comment]
@iblackly 这个问题我们优化一下

**Comment by iblackly** [comment]
@chhpt 大佬，我刚试了最新版，后台已经可以显示字符串和数字了，
但是 实际数据都是字符串~

![mu1](https://user-images.githubusercontent.com/3168355/97291082-6689f900-1884-11eb-86f8-7925c30dd506.png)
![mu0](https://user-images.githubusercontent.com/3168355/97291077-6558cc00-1884-11eb-9945-eda9a0ae02c3.png)
![mu2](https://user-images.githubusercontent.com/3168355/97291084-67bb2600-1884-11eb-955a-d49e0aeda122.png)
![mu3](https://user-images.githubusercontent.com/3168355/97291085-6853bc80-1884-11eb-8bc4-63c1848b4d1b.png)

**Comment by chhpt** [comment]
@iblackly 有 Bug，需要修复

**Comment by chhpt** [comment]
已修复
