### ISSUE TITLE
上传多张图片，会有部分图片路径被覆盖（上传4张不同的图片，上传不完全，且存在路径相同的情况）

### ISSUE THREAD

**Issue by big-jiang** [TencentCloudBase/cloudbase-extension-cms#4]
1.云存储实际情况
![image](https://user-images.githubusercontent.com/52397707/89849146-6dc13500-dbba-11ea-9d80-cc89a77c27d0.png)
2.CMS管理系统展示
![image](https://user-images.githubusercontent.com/52397707/89849174-83365f00-dbba-11ea-946c-6a2a115ce47c.png)
3.云数据库数据详情
![image](https://user-images.githubusercontent.com/52397707/89849227-a95bff00-dbba-11ea-9214-33d29fdfee0c.png)

基础信息：
环境id：wechat-50ql8

**Comment by chhpt** [comment]
@big-jiang  使用图片类型时，上传同名文件会产生相同的路径，并且会覆盖原有的图片，这个表现是符合预期的

**Comment by big-jiang** [comment]
> @big-jiang 使用图片类型时，上传同名文件会产生相同的路径，并且会覆盖原有的图片，这个表现是符合预期的

![image](https://user-images.githubusercontent.com/52397707/89850018-6569f980-dbbc-11ea-8f96-883f98bc780e.png)
都是不同的，
![image](https://user-images.githubusercontent.com/52397707/89850341-c1348280-dbbc-11ea-837f-50374d8bbbd1.png)
这个是CMS展示的
![image](https://user-images.githubusercontent.com/52397707/89850399-da3d3380-dbbc-11ea-9ef3-33052955da54.png)
上传的具体文件路径

如果是因为同名覆盖的话，云存储的路径最多不会超过5个
cloud://wechat-50ql8.7765-wechat-50ql8-1300882894/uploads/1597109222693.jpg
cloud://wechat-50ql8.7765-wechat-50ql8-1300882894/uploads/1597109606518.jpg
cloud://wechat-50ql8.7765-wechat-50ql8-1300882894/uploads/1597110662225.jpg
这三个都是一样的

**Comment by chhpt** [comment]
@big-jiang 这里是个 Bug，同时使用多个图片类型的时候，会出现文件名相同的情况

**Comment by big-jiang** [comment]
> @big-jiang 这里是个 Bug，同时使用多个图片类型的时候，会出现文件名相同的情况

好的，等你们修复。注：目前我用云存储直接上传图片+字符串数组。解决以上问题

**Comment by chhpt** [comment]
2.0 版本已修复了这个问题，请升级 2.0 版本
