### ISSUE TITLE
【建议】cms里面的弹窗锁定点击背景不要自动关闭，很容易误操作

### ISSUE THREAD

**Issue by seymoe** [TencentCloudBase/cloudbase-extension-cms#40]
正在尝试使用cms，添加字段的时候，就发现了这个点

**Comment by chhpt** [comment]
@seymoe 这个我们优化一下

**Comment by yekai9527** [comment]
这个问题我们也遇到过，确实还挺烦人的
不过怎么说呢，主要是在权限设置和模型管理部分有这个弹窗
总的来说这部分用户用的比较少
所以也没有提issue，不想给开发增加负担
坦白说
项目已经很好用了
腾讯的工程师真棒
加油鸭

**Comment by yekai9527** [comment]
我复现下场景
供工程师参考
其实问题不在于点击背景部分让弹窗关闭
而在于
比如我要编辑一个富文本
期间选中的时候
鼠标在按下状态
然后移动鼠标选择的时候
很容易把鼠标一下移动到背景位置
这时候放开鼠标
弹出消失了

这个经过我们使用
是最容易出现的误操作场景
影响其实挺大的

供您参考
不知道说清楚没
我在群里
没清楚我给你录屏

**Comment by chhpt** [comment]
@yekai9527 有问题，提 Issue 是可以的，合理的 Issue 有助于我们改善项目的使用体验

**Comment by chhpt** [comment]
就字段编辑场景，禁用了点击背景关闭弹窗

**Comment by seymoe** [comment]
@chhpt ok，这个先关了
