### ISSUE TITLE
建议增加json可视化编辑器

### ISSUE THREAD

**Issue by zhifengjiang** [TencentCloudBase/cloudbase-extension-cms#41]
进行数据编辑的一般为非技术人员，有的人对json格式不熟悉，使用可视化工具可以降低学习成本，并且可视化也可以提高编写速度，望支持。推荐[json-editor](https://github.com/josdejong/jsoneditor)
另外也希望支持定义json schema

**Comment by chhpt** [comment]
@zhifengjiang 已经支持了 JSON 的可视化编辑了，JSON Schema 暂时不会支持。

**Comment by chhpt** [comment]
Close with no reply
