### ISSUE TITLE
希望支持数据表格顶部固定

### ISSUE THREAD

**Issue by jiangqidu** [TencentCloudBase/cloudbase-extension-cms#42]
当数据一多的时候，顶部的信息就会被刷到最上面，从而无法看到对应的数据字段名，希望加入数据表格顶部固定

**Comment by jiangqidu** [comment]
-
![0d344108797fdca827ea73ee681d947](https://user-images.githubusercontent.com/55723376/97249803-8ba84880-183f-11eb-8f03-80d4c9d80259.png)
![Uploading 100984284c4d9d24596e9f97cd8cd14.png…]()

**Comment by chhpt** [comment]
@jiangqidu 整体上来说，固定的体验不如不固定，在单页数据 10 条的情况下，不固定的体验也是可以的。
