### ISSUE TITLE
在此对维护者无亦杨的感谢

### ISSUE THREAD

**Issue by yekai9527** [TencentCloudBase/cloudbase-extension-cms#43]
感谢提供了如此好的开源项目!
可惜我只能贡献一颗星星
如果我有三头六臂
我会给你好多星星 star star 一闪一闪亮晶晶

**Comment by chhpt** [comment]
@yekai9527 感谢支持~

**Comment by xmsz** [comment]
这个项目确实很有意义 而且真的很有用

我们最近再搞一些小项目，如果按照以往的开发节奏肯定不够快

所以用了腾讯云开发（阿里的还没完善不好对比）一把梭

不过之前我们有开发过微信公众号和小程序，被微信开发团队搞得怕死了，bug又多又不改，还怕更新以前的也坏了...

但是用腾讯云开发的时候，感觉真的巨牛逼，想到的都有。


比如就这个cms系统，只能说真的极度刚需

我们虽然可以用1天时间可以开发完前台的前后端，但是后台是个大问题，如果没有后台对运营者实在太不友好了

可以说产品能不能成功80%就得看运营，做个好工具帮助运营就是最重要的事情

而如果这个后台还要自己从0开始写，太浪费时间，不符合快节奏

后来看到这个项目真的爽死了，安装方便，基础功能完善。我们这次的项目需求全部满足。太牛了



而且还给了我们一个很好的思路，我们一直有打算搞个产品管理平台，管理开发和运营环节。
因为市面上的都不符合我们的需求。运营环节基本没有，因为运营和业务需要深度的结合，用第三方还不如自己开发集成。除非搞无代码，当然这个肯定不可能... 运营又不是开发。
而开发环节呢，这里就要讲一下coding，搞不懂明明可以搞成一个创业公司小而美的项目。但现在搞得跟集团产品一样。看得出野心但现在真不实用。当然国外的工具最大问题还是访问速度所以就放弃了


总之这个项目真的有棒~
