### ISSUE TITLE
cms后台管理图片数组在对应文件被删除以后无法编辑

### ISSUE THREAD

**Issue by yekai9527** [TencentCloudBase/cloudbase-extension-cms#44]
假设某个图片数组在数据库存储如图

[
	‘cloudid-1-图片1’,
	‘cloudid-2-图片2’
	‘cloudid-3-图片3’
]

云存储中,对应有三个文件
/
cloudid-1-图片1
cloudid-2-图片2
cloudid-3-图片3

现在假设我删除了云存储中的任意一张图片,此时数据库不变
[
	‘cloudid-1-图片1’,
	‘cloudid-2-图片2’
	‘cloudid-3-图片3’
]

但是云存储中少了一张图,变成了两个文件
/
cloudid-2-图片2
cloudid-3-图片3

这个时候,需要加入一张新的图片 clouded-4-图片4,通过cms,怎么都编辑不成功,总是失败,只有在数据库中删除所有之前的图片,也就是将数据库中
[
	‘cloudid-1-图片1’,
	‘cloudid-2-图片2’
	‘cloudid-3-图片3’
]
设置为空 [] 然后cms才可以重新编辑图片

**Comment by chhpt** [comment]
建议不要随意删除已经上传的文件
