### ISSUE TITLE
内容集合新增图片

### ISSUE THREAD

**Issue by TomWangKing** [TencentCloudBase/cloudbase-extension-cms#48]
新增图片内容时候上传完自动跳转回列表页，还没有按新建按钮确定，会是因为Webbook原因吗，没见新建成功

**Comment by chhpt** [comment]
无法复现这个问题，能提供一下详细的复现步骤吗

**Comment by TomWangKing** [comment]
这个好像和Webbook推送是一起的，没有Webbook推送好像不会出现，需要刚修改完Webbook，并且是Webbook推送地址是错误的，然后去集合中新增图片才会出现，过几分钟就好了

**Comment by TomWangKing** [comment]
有时候出现有时候不出现

**Comment by chhpt** [comment]
最好能提供复现的 Demo 哈

**Comment by chhpt** [comment]
没有回复，关闭 Issue
