### ISSUE TITLE
Webbook推送问题

### ISSUE THREAD

**Issue by TomWangKing** [TencentCloudBase/cloudbase-extension-cms#49]
只有一个Webbook，监听一个集合的创建，但是删除功能也会推送到Webbook上，Webbook链接没有设置删除推送

**Comment by chhpt** [comment]
请问你是否选择了全部选项

**Comment by TomWangKing** [comment]
Webhook 名称   
***
Webhook 描述

触发 URL
https://**.***.com/

监听内容
**集合

触发事件
创建内容

HTTP 方法
POST


HTTP Headers

**Comment by chhpt** [comment]
无法复现这个问题，麻烦在 https://cms-demo-1252710547.tcloudbaseapp.com 这个 Demo 中复现问题哈~ 
账号： cmsAdmin
密码： cmsAdmin123==

**Comment by chhpt** [comment]
是个 Bug

**Comment by TomWangKing** [comment]
还需要我上传测试案例吗

**Comment by chhpt** [comment]
Fix in v2.3.0
