### ISSUE TITLE
提两点操作体验上的小建议

### ISSUE THREAD

**Issue by ichizi** [TencentCloudBase/cloudbase-extension-cms#55]
![image](https://user-images.githubusercontent.com/7540755/99874837-c1b1d000-2c25-11eb-8574-2b2c43f5781e.png)
1、筛选条件其实大部分情况下都是固定的几个，所以检索定义能否保存下来？下次访问这个集合的时候，可以直接用。
2、「创建时间」、「更新时间」并不需要，能否可以配置它，默认不展示，或者定义模型的时候，可以配置这俩不展示。

**Comment by chhpt** [comment]
Release in v2.6.0
