### ISSUE TITLE
表的多层关联问题：c表的字段，关联b表的字段b1，而b1也是关联的a表的字段a1，给c表新增数据的时候就报错了

### ISSUE THREAD

**Issue by xing393939** [TencentCloudBase/cloudbase-extension-cms#58]
![1](https://user-images.githubusercontent.com/2681291/101359235-f3d65980-38d6-11eb-80e5-73a2fe3dac18.png)
当给c表新增数据的时候，点击上图的地方就报错了，报错截图如下：
![2](https://user-images.githubusercontent.com/2681291/101359334-11a3be80-38d7-11eb-835a-c5f559470726.png)
js的错误信息如下：
![3](https://user-images.githubusercontent.com/2681291/101359356-19fbf980-38d7-11eb-82b6-98b7ece12a17.png)

希望能支持这种多层关联的场景，谢谢！

**Comment by chhpt** [comment]
fixed in v2.5.0
