### ISSUE TITLE
希望可以设置某些表不出现在菜单栏（管理员可写，其他用户不可见）

### ISSUE THREAD

**Issue by xing393939** [TencentCloudBase/cloudbase-extension-cms#59]
比如有一个专门存商品分类的表，只需要管理员一次性把商品的分类录入好了，之后其他表直接关联就行了。并不需要其他用户去curd。
这样的话，可以在开始的时候由管理员录入好了数据，然后把这个商品分类表设置成隐藏，即不需要出现在左侧的菜单里面。

**Comment by chhpt** [comment]
当前支持通过权限控制区分展示不同的集合信息，请参考用户权限设置：https://docs.cloudbase.net/cms/usage/permission.html
