### ISSUE TITLE
刚部署了一个cms，发现资源加载路径不正确

### ISSUE THREAD

**Issue by DaZiYuan** [TencentCloudBase/cloudbase-extension-cms#6]
测试网页：
https://livewallpaper-0sikk-1302505715.tcloudbaseapp.com/cms

![image](https://user-images.githubusercontent.com/80653/90355257-69938c80-e07e-11ea-9595-0955a237c984.png)

错误地址
https://livewallpaper-0sikk-1302505715.tcloudbaseapp.com/static/css/main.47fc05c6.chunk.css
正确地址
https://livewallpaper-0sikk-1302505715.tcloudbaseapp.com/cms/static/css/main.47fc05c6.chunk.css

**Comment by chhpt** [comment]
@DaZiYuan 你是通过什么方法部署的？

**Comment by DaZiYuan** [comment]
腾讯云后台》内容管理

**Comment by chhpt** [comment]
@DaZiYuan  这边看你的 CMS 是部署在根路径了

**Comment by chhpt** [comment]
@DaZiYuan https://livewallpaper-0sikk-1302505715.tcloudbaseapp.com/#/login

**Comment by DaZiYuan** [comment]
我刚才在测试，跟路径可以。
但是默认路径的tcb-cms似乎不行

**Comment by chhpt** [comment]
这个路径是你部署时填写的路径，

<img width="960" alt="Xnip2020-08-17_11-52-17" src="https://user-images.githubusercontent.com/19288423/90355855-3225df80-e080-11ea-8873-162543034c77.png">

@DaZiYuan

**Comment by DaZiYuan** [comment]
不好意思打扰了，我地址输错了
https://livewallpaper-0sikk-1302505715.tcloudbaseapp.com/tcb-cms
改成
https://livewallpaper-0sikk-1302505715.tcloudbaseapp.com/tcb-cms/index.html
正常
