### ISSUE TITLE
关于内容模型配置的一些建议

### ISSUE THREAD

**Issue by chao** [TencentCloudBase/cloudbase-extension-cms#64]
希望能在内容模型配置的时候可以设置这个模型中那些列在列表页面中显示，是否启用排序。默认排序方式，以及展示的优先级（显示在第几列）。

**Comment by chhpt** [comment]
![image](https://user-images.githubusercontent.com/19288423/102161101-a7d07980-3ec1-11eb-8776-8fb537267282.png)
