### ISSUE TITLE
在导出的模型json文件中应该带有版本信息

### ISSUE THREAD

**Issue by chao** [TencentCloudBase/cloudbase-extension-cms#65]
目前我遇到一个bug，就是在2.30导出的模型文件导入到2.40后那个模型就管理不了。后来经过分析是发现2.30到2.40的模型文件发生了变化。

所以在导入模型文件的时候应该检测一下导出的模型文件版本是否兼容，不兼容则不允许导入。

**Comment by chhpt** [comment]
你遇到的情况是 Bug，并非是不兼容问题
