### ISSUE TITLE
导入多个模型文件的时候异常

### ISSUE THREAD

**Issue by chao** [TencentCloudBase/cloudbase-extension-cms#66]
目前导入模型文件的时候是可以一个个文件拖到文件上传区域（这时候下方列表会显示多个文件）
![image](https://user-images.githubusercontent.com/55872/102157829-2d046000-3ebb-11eb-801c-f283eecb7fbe.png)

这样用户会误以为导入模型文件的时候支持多个文件同时导入。但是实际上只导入了一个文件。

建议要么修改为只能导入一个文件（拖第二个文件进去的时候替换掉第一个文件）

要么修改为支持拖动多个文件到文件上传列表，支持一次性导入多个文件。

**Comment by chhpt** [comment]
v2.5.1 支持导入多个模型文件
