### ISSUE TITLE
新建角色权限问题

### ISSUE THREAD

**Issue by jerrylee007** [TencentCloudBase/cloudbase-extension-cms#69]
<img width="1074" alt="Screen Shot 2020-12-26 at 3 56 36 PM" src="https://user-images.githubusercontent.com/1650382/103147721-0b488a00-4793-11eb-896f-58d5170be71d.png">
如图，我只希望能对《菜单》和《温馨提示》有编辑权限，结果这些编辑权限对第一栏的所有项目都会生效

**Comment by chhpt** [comment]
@jerrylee007  你的意思是指：这个角色也能编辑客人，菜单等集合吗

**Comment by jerrylee007** [comment]
> @jerrylee007 你的意思是指：这个角色也能编辑客人，菜单等集合吗

是的

**Comment by chhpt** [comment]
@jerrylee007 能提供复现的 Demo 吗？另外，默认情况下，是能看见操作按钮的，但是没有操作的权限。

**Comment by chhpt** [comment]
close for no response
