### ISSUE TITLE
多媒体类型（音频/视频）支持“允许多个内容” + 多个内容之间可以拖拽排序

### ISSUE THREAD

**Issue by KJlmfe** [TencentCloudBase/cloudbase-extension-cms#73]
目前，仅有文件类型支持：允许多个内容（在创建内容时，允许创建多个内容，数据将以数组格式存储）

希望多媒体类型（音频/视频），也能支持允许多个内容

并且可以支持多个内容的数据，可以拖拽调整顺序

**Comment by chhpt** [comment]
多媒体类型（音频/视频）已支持多个内容
