### ISSUE TITLE
能否支持单集合录入多种物品数据？

### ISSUE THREAD

**Issue by iblackly** [TencentCloudBase/cloudbase-extension-cms#77]
目前不同类型的物品放在各自的集合中，
如果用户收藏了 A到Z 集合中不同的物品，
那么根据 物品集合名和物品ID 去lookup，我总觉得很麻烦~

我的想法是将所有物品放到一个集合内！
这样很多查询功能很容易实现！
lookup的次数就会变少！

所以希望CMS能支持单集合录入多种数据！
感谢！

**Comment by rayyzhong** [comment]
你为什么要放在多个集合？

**Comment by iblackly** [comment]
> 你为什么要放在多个集合?

啊..这.. 因为不太了解NOSQL，就全分开了，，，
所以现在正在改，每个类型的表单都不太一样，
所以目前CMS可以录入多种类型的数据，
但是如果能根据类型动态显示表单就更好了~
不然录入页面有特别多无关的内容。

**Comment by chhpt** [comment]
@iblackly  这个与 CMS 的系统设计违背，无法实现

**Comment by iblackly** [comment]
> @iblackly  这个与 CMS 的系统设计违背，无法实现

好的大佬，
我用hook + http云函数 实现了，
感谢大佬👍
