### ISSUE TITLE
内容设置中 图标设置的弹窗显示404

### ISSUE THREAD

**Issue by tza17313** [TencentCloudBase/cloudbase-extension-cms#8]
`packages/tcb-ext-cms-admin/package.json` 依赖的 **react-material-ui-icon-picker** 太久没更新；
导致依赖的iconfont codepoints 路径错误；
https://github.com/DMDc0de/material-ui-icon-picker/blob/master/src/IconsStorage.js#L32

需要在 material-ui-icon-picker 中把 `/src/IconsStorage.js`里
https://raw.githubusercontent.com/google/material-design-icons/master/iconfont/codepoints 改为
https://raw.githubusercontent.com/google/material-design-icons/v2.1.3/iconfont/codepoints

改动参考：
https://github.com/DMDc0de/material-ui-icon-picker/compare/master...tza17313:master

建议你们把`react-material-ui-icon-picker`包的内容，放在项目内单独的组件，毕竟这个包只发布过一个版本，且3年多没更新了；

**Comment by binggg** [comment]
👍

**Comment by chhpt** [comment]
@tza17313 感觉你的建议，不过我们在 V2 版本中移除了此库。
