### ISSUE TITLE
RESTful API 查询嵌套文档时无法使用点语法

### ISSUE THREAD

**Issue by lipd** [TencentCloudBase/cloudbase-extension-cms#86]
我的文档结构大概是这样
<img width="1198" alt="Screen Shot 2021-02-09 at 3 54 07 PM" src="https://user-images.githubusercontent.com/25012301/107332682-70f89780-6aef-11eb-8837-ed3c2a12e574.png">

我按照文档中查询嵌套文档和使用点语法都无法查询到结果。
<img width="524" alt="Screen Shot 2021-02-09 at 3 55 36 PM" src="https://user-images.githubusercontent.com/25012301/107332720-7ce45980-6aef-11eb-8476-19340d78422a.png">

我想了解一下如何才能正确查询到嵌套的文档？

修改：
我之前的描述可能有问题，我的需求是通过一个关联字段来查询到文档，现在貌似不能通过关联字段进行查询，请问有通过关联字段查询文档的方法吗？

**Comment by lipd** [comment]
不好意思，我刚刚发现使用 query command 可以查询到嵌套文档。

**Comment by chhpt** [comment]
close for no response
