### ISSUE TITLE
使用枚举创建或修改 数字类型元素时，存入数据库的类型为String

### ISSUE THREAD

**Issue by double-fire-0** [TencentCloudBase/cloudbase-extension-cms#90]
![image](https://user-images.githubusercontent.com/69890917/109423226-9ce5a980-7a19-11eb-9720-1d86fa8500c5.png)
**已经选择了枚举类型为数字，但是存入数据库中后，在数据库中显示的类型为string。
试了好几次都是一样的结果，有其他同事遇到过这种错误嘛？还是我的配置问题
感觉这个还是一个挺严重的bug的，希望尽快修复。**

**Comment by chhpt** [comment]
目前没有复现这个问题，麻烦提供可以复现问题的 Demo

**Comment by chhpt** [comment]
close for no response
