### ISSUE TITLE
二次开发-如何选择云环境

### ISSUE THREAD

**Issue by JessYan0913** [TencentCloudBase/cloudbase-extension-cms#91]
由于项目紧急，选择了CMS做管理端。但是现在CMS只能实现内容编辑和查看等功能，遇到内容**审核**逻辑时十分鸡肋。看到开发进度中，正在进行字段可编辑功能开发。不知道什么时候才能上线，所以无奈选择了二次开发。

如何在二次开发中，只二次开发前端页面。后台服务依旧使用原来的云函数？

**Comment by JessYan0913** [comment]
大佬们，有没有合适的解决方案？

**Comment by chhpt** [comment]
这个要结合你的需求来看，不能一概而论，有需要的话，还是要修改云函数的代码的

**Comment by JessYan0913** [comment]
现在的需求是，要求详情页不可编辑，但是要添加审核按钮。如果可以只二次开发前端的话，可以只添加一个按钮，给按钮绑定一个云函数钩子。也是可以实现对吧？

**Comment by JessYan0913** [comment]
另外，个人觉得CMS可以开放一些页面钩子，让页面更具定制性

**Comment by chhpt** [comment]
扩展性在设计中

**Comment by JessYan0913** [comment]
最终决定放弃了！不过还是希望CMS越做越好！！！
扩展性计划中，希望增加页面扩展性！页面级的钩子！
官方可以参考一下https://github.com/YMFE/yapi的模式
