### ISSUE TITLE
枚举内容类型是否可以支持多选？

### ISSUE THREAD

**Issue by YuniorZen** [TencentCloudBase/cloudbase-extension-cms#92]
cms的内容模型有枚举字段，可用于字段单选的数据处理，有时候一个字段存在多选的场景，不知道后续是否能考虑支持一下多选的枚举类型？
![image](https://user-images.githubusercontent.com/6168355/110312800-8a362a80-8040-11eb-92b2-34bfbec716d0.png)

**Comment by chhpt** [comment]
重复需求：https://github.com/TencentCloudBase/cloudbase-extension-cms/issues/72
