### ISSUE TITLE
编辑模型字段中的非数据库字段名提示“更新字段失败:已存在同名字段xx，请勿重复创建”

### ISSUE THREAD

**Issue by timooabc** [TencentCloudBase/cloudbase-extension-cms#94]
场景：
模型中，添加了一个字段，但是后来想修改一下描述信息或者其他非“数据库字段名”的属性

结果：
点击按钮“更新”提示“更新字段失败:已存在同名字段xx，请勿重复创建”。无法更新信息。

目前解决办法：
删除字段，重新加字段。

预期：
在不调整数据库字段名时，能够在原先的字段上提交修改过的内容。

谢谢

**Comment by chhpt** [comment]
已修复 -> v2.8.3
